# Copyright (c) Facebook, Inc. and its affiliates.

device: cpu

problem_name: rpca

robust_PCA_p: 30
robust_PCA_q: 3
num_iterations_train: 15
num_iterations_eval: 15

lr: 1e-3
beta1: 0.9
beta2: 0.99
cosine_lr_decay: False
seed: 0
use_train_seed: false
train_seed: 0
train_data_seed: 0

scs:
  use_problem_scaling: True
  scale: 1
  rho_x: 1e-3
  alpha: 1.5

rec_model:
  _target_: accel.NeuralLSTM
  rec_n_hidden: 256
  rec_n_layers: 2
  init_hidden_depth: 2
  init_hidden_n_hidden: 512
  init_hidden_weight_scale: 1.
  init_act: relu
  enc_hidden_depth: 0
  enc_n_hidden: 512
  enc_weight_scale: 1.
  enc_act: relu
  dec_hidden_depth: 2
  dec_n_hidden: 512
  dec_weight_scale: 10.
  dec_act: relu
  learn_init_iterate: True
  learn_init_hidden: True
  device: cpu

model:
  _target_: accel.NeuralLSTM
  rec_n_hidden: 256
  rec_n_layers: 2
  init_hidden_depth: 2
  init_hidden_n_hidden: 512
  init_hidden_weight_scale: 1.
  init_act: relu
  enc_hidden_depth: 0
  enc_n_hidden: 512
  enc_weight_scale: 1.
  enc_act: relu
  dec_hidden_depth: 2
  dec_n_hidden: 512
  dec_weight_scale: 10.
  dec_act: relu
  learn_init_iterate: True
  learn_init_hidden: True
  device: cpu

use_sparse_matrix: True
use_jitted_cones: True
unscale_before_model: False
regularize: 0.0
use_unscaled_loss: True

num_train_instances: 1000
num_validate_instances: 50
num_test_instances: 50
train_batch_size: 50
test_batch_size: 50  # num_test_instances must be an exact multiple of test_batch_size for current jit
validate_batch_size:  50
train_graph_batch_size: 2
test_graph_batch_size: 2
validate_graph_batch_size: 2

num_model_updates: 1e3

clip_gradients: True
max_gradient: 100

test_freq: 100
save_freq: 1000
log_tensorboard: True
tensorboard_dir: runs

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}.scs
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}.scs
    subdir: ${hydra.job.num}